[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }

[build]

rustdocflags = []

[target.x86_64-pc-windows-msvc]
linker = "rust-lld"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
rustflags = [
  "--cfg",
  "tokio_unstable",
  "-Zshare-generics=y",
  "-Csymbol-mangling-version=v0",
  "-Ctarget-feature=-crt-static",
  "-Clink-arg=-lgcc",
]

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.'cfg(all())']
rustflags = [
  "--cfg",
  "tokio_unstable",
  "-Zshare-generics=y",
  "-Csymbol-mangling-version=v0",
  "-Aclippy::too_many_arguments",
  # Clippy's needless mut lint is buggy: https://github.com/rust-lang/rust-clippy/issues/11299
  "-Aclippy::needless_pass_by_ref_mut",
  # Clippy's partial_eq lint is buggy: https://github.com/rust-lang/rust-clippy/issues/11178
  "-Aclippy::incorrect_partial_ord_impl_on_ord_type",
]
